"""recreate_test_table

Revision ID: 2df5c6c17b2a
Revises: e39fc5763c4c
Create Date: 2025-04-05 04:13:23.357915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df5c6c17b2a'
down_revision: Union[str, None] = 'e39fc5763c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
