"""recreate_test_table

Revision ID: 4b2a9f580ab9
Revises: d17ec93bb56b
Create Date: 2025-04-05 04:04:12.225094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b2a9f580ab9'
down_revision: Union[str, None] = 'd17ec93bb56b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
